# docker/Dockerfile.frontend

# 1. Build stage
FROM node:20 AS builder
WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy app source
COPY . .
RUN npm run build

# 2. Run stage
FROM node:20-alpine
WORKDIR /app

# Copy only production build and necessary files
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
COPY --from=builder /app/package*.json ./

RUN npm install --omit=dev

EXPOSE 3000
CMD ["npm", "run", "start"]