from __future__ import annotations

import uuid
from datetime import datetime
from enum import Enum

from sqlalchemy import JSON, DateTime, Enum as SAEnum, Integer, String, Text, func
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlalchemy.orm import Mapped, mapped_column

from .session import Base


class JobStatus(str, Enum):
    """Status of a job execution."""

    queued = "queued"
    running = "running"
    completed = "completed"
    failed = "failed"


class JobType(str, Enum):
    """Types of AI tasks supported by the platform."""

    text_generation = "text_generation"
    speech_to_text = "speech_to_text"
    text_to_speech = "text_to_speech"
    image_generation = "image_generation"
    image_to_text = "image_to_text"
    embeddings = "embeddings"


class ModelBackend(str, Enum):
    """Available model backends."""

    ollama = "ollama"
    mlx = "mlx"
    pytorch = "pytorch"
    gguf = "gguf"
    whisper = "whisper"


class Model(Base):
    """Registered AI models."""

    __tablename__ = "models"

    id: Mapped[uuid.UUID] = mapped_column(
        PG_UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    name: Mapped[str] = mapped_column(String(255), unique=True, nullable=False)
    backend: Mapped[ModelBackend] = mapped_column(
        SAEnum(ModelBackend, name="model_backend_enum"), nullable=False
    )
    # Supported task types - JSON array of JobType values
    supported_tasks: Mapped[list] = mapped_column(
        JSON,
        nullable=False,
        default=lambda: ["text_generation"],
        server_default='["text_generation"]',
    )
    config: Mapped[dict] = mapped_column(JSON, nullable=False, default=dict)
    description: Mapped[str | None] = mapped_column(Text, nullable=True)
    is_active: Mapped[bool] = mapped_column(default=True, nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False
    )


class Job(Base):
    """Job execution records."""

    __tablename__ = "jobs"

    id: Mapped[uuid.UUID] = mapped_column(
        PG_UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    model_name: Mapped[str] = mapped_column(String(255), nullable=False)
    backend: Mapped[ModelBackend] = mapped_column(
        SAEnum(ModelBackend, name="model_backend_enum"), nullable=False
    )
    # Task type - defaults to text_generation for backward compatibility
    task_type: Mapped[JobType] = mapped_column(
        SAEnum(JobType, name="job_type_enum"),
        nullable=False,
        default=JobType.text_generation,
        server_default="text_generation",
    )
    prompt: Mapped[str] = mapped_column(Text, nullable=False)
    # Input files for multi-modal tasks (JSON array of file paths)
    input_files: Mapped[list] = mapped_column(
        JSON, nullable=False, default=list, server_default="[]"
    )
    # Output files generated by the task (JSON array of file paths)
    output_files: Mapped[list] = mapped_column(
        JSON, nullable=False, default=list, server_default="[]"
    )
    parameters: Mapped[dict] = mapped_column(JSON, nullable=False, default=dict)
    result: Mapped[dict | None] = mapped_column(JSON, nullable=True)
    status: Mapped[JobStatus] = mapped_column(
        SAEnum(JobStatus, name="job_status_enum"), nullable=False, default=JobStatus.queued
    )
    error_message: Mapped[str | None] = mapped_column(Text, nullable=True)
    execution_time_ms: Mapped[int | None] = mapped_column(Integer, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    started_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    completed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
